"""empty message

Revision ID: 13dad3f9002f
Revises: 91bee6899267
Create Date: 2016-03-30 18:18:32.473232

"""

# revision identifiers, used by Alembic.
revision = '13dad3f9002f'
down_revision = '91bee6899267'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
