"""empty message

Revision ID: 91bee6899267
Revises: f5b1a93a29ea
Create Date: 2016-03-30 18:14:35.951473

"""

# revision identifiers, used by Alembic.
revision = '91bee6899267'
down_revision = 'f5b1a93a29ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contextname', sa.String(length=500), nullable=True),
    sa.Column('start_time', sa.String(length=50), nullable=True),
    sa.Column('end_time', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('context_show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('articlename', sa.String(length=50), nullable=True),
    sa.Column('timelimit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('context_show')
    op.drop_table('context_list')
    ### end Alembic commands ###
