"""empty message

Revision ID: a48ecb6c7050
Revises: 13dad3f9002f
Create Date: 2016-03-30 18:27:06.440350

"""

# revision identifiers, used by Alembic.
revision = 'a48ecb6c7050'
down_revision = '13dad3f9002f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
