"""empty message

Revision ID: ada17b32c8fe
Revises: a48ecb6c7050
Create Date: 2016-03-30 18:43:03.067066

"""

# revision identifiers, used by Alembic.
revision = 'ada17b32c8fe'
down_revision = 'a48ecb6c7050'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
