"""empty message

Revision ID: f5b1a93a29ea
Revises: fee089fdee78
Create Date: 2016-03-30 18:12:51.765973

"""

# revision identifiers, used by Alembic.
revision = 'f5b1a93a29ea'
down_revision = 'fee089fdee78'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
